### ISSUE TITLE
Plugin Error: SingletonTest threw an uncaught EmptyThrowable

### ISSUE THREAD

**Issue by macouen** [luhaoaimama1/SingletonTest#3]
EmptyThrowable: Icon cannot be found in '../res/icon.jpg', aClass='class templete.SingletonAction'

Android Studio 2.3.2 
Windows 8.1

**Comment by duodebuyali** [comment]
the same problem

Android Studio 2.3.1
mac 10.13.2

**Comment by luhaoaimama1** [comment]
1.2 is ok  .now is Uploading audit ，may use 
https://github.com/luhaoaimama1/SingletonTest/blob/master/SingletonTest.jar
